# Generated by Django 5.0.1 on 2024-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
